### PR TITLE
Fixes frozen cursor issue when double-clicking on transform UI tab.

### LINKED ISSUE #32: Double-clicking shape transform tabs leaves cursor in a bad state
When double-clicking the interactive transforms tabs of a selected shape, the cursor suddenly freezes. The below gif is a capture of the issue using the exampeShapeBuilder example:

mapd-draw-doubleclick-issue

### PR DESCRIPTION
**Pull request by vastcharade**
Fixes #32

### CODE REVIEW

File: src/engine/shape-builder.js [hunk 1]
```diff
@@ -685,6 +677,8 @@ export default class ShapeBuilder extends DrawEngine {
       }
       this._dragInfo = null
       clearSelectedShapes(this._selectedShapes)
+      removeCustomCursor()
+      setCursorState(this._parent, "default", "auto", false)
```
Comment (vastcharade) [inline src/engine/shape-builder.js]: These 2 lines of code ultimately fix the bug
